name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U "jupyterlab>=4.0.0,<5"

    - name: Lint the extension
      run: |
        set -eux
        npm run lint:check

    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]

        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "urncjp.*OK"

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "urncjp.*OK"
        python -m jupyterlab.browser_check

    - name: Package the extension
      run: |
        set -eux

        pip install build
        python -m build
        pip uninstall -y "urncjp" jupyterlab

    - name: Upload extension packages
      uses: actions/upload-artifact@v4
      with:
        name: extension-artifacts
        path: dist/urncjp*
        if-no-files-found: error
