name: Build and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/urncjp
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: |
        npm install
        python -m pip install -U "jupyterlab>=4.0.0,<5"

    - name: Lint the extension
      run: |
        set -eux
        npm run lint:check

    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]

        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "urncjp.*OK"

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "urncjp.*OK"
        python -m jupyterlab.browser_check

    - name: Package the extension
      run: |
        set -eux

        pip install build
        python -m build
        pip uninstall -y "urncjp" jupyterlab
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Publish the extension to npm
      run: |
        set -eux
        npm publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

